#!/usr/bin/env bash
# script to install nginx on a server

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www
echo 'Hello World!' > /var/www/html/index.html
