#!/usr/bin/env bash
# script to install nginx on a server

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www
echo 'Hello World!' > /var/www/html/index.html

redct="location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

sed -i "s|# SSL configuration|$redct|" /etc/nginx/sites-available/default
