#!/usr/bin/env bash
# script to install nginx on a server
# configure response header to track server

sudo apt update
sudo apt install -y nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www
sudo echo 'Hello World!' > /usr/share/nginx/html/index.html
sudo echo 'Hello World!' > /var/www/html/index.html

header="# Basic Settings\n\tadd_header X-Served-By `hostname`;"

sudo sed -i "s|# Basic Settings|$header|" /etc/nginx/nginx.conf

sudo nginx -s reload
