#!/usr/bin/env bash
# script to configure a load balancer on a new server

# install haproxy
sudo apt update
sudo apt-get install -y haproxy

# Configure HAproxy so that it send traffic to web-01 and web-02
# distribute using round robin
cmd="
frontend haproxynode
        bind *:80
        mode http
        default_backend backendnodes

backend backendnodes
        balance roundrobin
        server 56580-web-01 54.236.25.236:80 check
        server 56580-web-02 54.173.164.226:80 check
"

sudo chown -R "$USER":"$USER" /etc/haproxy/
echo "$cmd" >> /etc/haproxy/haproxy.cfg
sudo mkdir /run/haproxy/
sudo haproxy -f /etc/haproxy/haproxy.cfg
