#!/usr/bin/env bash
# fixed a web server configuration that was preventing it from listining
rm /etc/nginx/sites-enabled/default;
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
