#!/usr/bin/env bash
#bash script that displayes number from 1 to 100
i=1
while [ $i -lt 101 ];do
	if [ 0 -eq $((i%15)) ]
	then
		echo 'FizzBuzz'
	elif [ 0 -eq $((i%3)) ]
	then
		echo 'Fizz'
	elif [ 0 -eq $((i%5)) ]
	then
		echo 'Buzz'
	else
		echo "$i"
	fi
		
	i=$((i+1))
done
