#!/usr/bin/env bash
# parses an Apache log file and displays the IP and HTTP_code for each visitor, and with the number of occurences.

awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr
